dotfiles_repo: https://github.com/cipaterson/dotfiles.git
dotfiles_repo_versio: main
configure_dotfiles: false

homebrew_taps:
  - federico-terzi/espanso

homebrew_uninstalled_packages:
  - cowsay

homebrew_installed_packages:
  - espanso
  - borgbackup

homebrew_cask_apps:
  - Joplin
    ## - aText  replaced by espanso!
  - google-drive
  - dropbox
  - stretchly
  - rectangle
  - anydesk
  - Flycut
  - vlc
  - visual-studio-code
  - romkatv/powerlevel10k/powerlevel10k
  ## - dozer  # or hidden or some other menu items manager
  ## - filezilla # There is no cask

mas_installed_apps:
  #  - { id: 443987910, name: "1Password" }
  #  - { id: 498486288, name: "Quick Resizer" }
  #  - { id: 557168941, name: "Tweetbot" }
  ##  - { id: 497799835, name: "Xcode" }
  - { id: 405399194, name: "Kindle" }
  - { id: 1103915944, name: "Greeenshot" }

# TODO: You don't have write permissions for the /Library/Ruby/Gems/2.6.0 directory
#gem_packages:
#  - name: bundler
#    state: latest

#npm_packages:
#  - name: webpack

#pip_packages:
#  - name: mkdocs

configure_dock: true
dockitems_remove:
  - TV
  - Maps
  - Podcasts
  - News
  - Keynote
  - "App Store"
dockitems_persist:
  - name: "Visual Studio Code"
    path: "/Applications/Visual Studio Code.app/"
    pos: 5
  - name: "Terminal"
    path: "/System/Applications/Utilities/Terminal.app/"
    pos: 6
